-- Moves recipe ingredients from free-text names to references into ingredient_suggestions.
-- Run once against Postgres before deploying the ingredient suggestion change. Safe to re-run.
--
-- Each distinct existing name (case-insensitive) becomes a suggestion, every recipe line is
-- pointed at its suggestion, and the old recipe_ingredients.name column is dropped.
-- Everything runs in one transaction: if any line cannot be matched, nothing changes.

BEGIN;

CREATE TABLE IF NOT EXISTS ingredient_suggestions (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ingredient_suggestions_name ON ingredient_suggestions (name);

ALTER TABLE recipe_ingredients ADD COLUMN IF NOT EXISTS suggestion_id bigint;
ALTER TABLE recipe_ingredients ADD COLUMN IF NOT EXISTS is_optional boolean NOT NULL DEFAULT false;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'recipe_ingredients' AND column_name = 'name') THEN

        INSERT INTO ingredient_suggestions (name)
        SELECT DISTINCT ON (lower(trim(ri.name))) trim(ri.name)
        FROM recipe_ingredients ri
        WHERE trim(ri.name) <> ''
          AND NOT EXISTS (SELECT 1 FROM ingredient_suggestions s WHERE lower(s.name) = lower(trim(ri.name)))
        ORDER BY lower(trim(ri.name)), trim(ri.name);

        UPDATE recipe_ingredients ri
        SET suggestion_id = (SELECT min(s.id) FROM ingredient_suggestions s
                             WHERE lower(s.name) = lower(trim(ri.name)))
        WHERE ri.suggestion_id IS NULL;

        ALTER TABLE recipe_ingredients DROP COLUMN name;
    END IF;
END $$;

ALTER TABLE recipe_ingredients ALTER COLUMN suggestion_id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_recipe_ingredients_suggestion') THEN
        ALTER TABLE recipe_ingredients
            ADD CONSTRAINT fk_recipe_ingredients_suggestion
            FOREIGN KEY (suggestion_id) REFERENCES ingredient_suggestions (id);
    END IF;
END $$;

COMMIT;

-- Optional: trigram index so the type-ahead's substring LIKE on lower(name) can use an index.
-- Kept outside the transaction because CREATE EXTENSION needs privileges some hosts withhold;
-- if it fails, search still works, it just scans the table.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_ingredient_suggestions_name_trgm
    ON ingredient_suggestions USING gin (lower(name) gin_trgm_ops);
