-- Seeds ingredient_suggestions with 322 curated FinalFoods entries
-- (duplicates and prepared dishes removed from the original 363).
-- Idempotent: names already present (case-insensitive) are skipped, so it is safe to re-run.

INSERT INTO ingredient_suggestions (name)
SELECT DISTINCT ON (lower(v.name)) v.name
FROM (VALUES
    ('Commercial Hummus'),
    ('Raw Grape Tomatoes'),
    ('Unheated Beef Frankfurter'),
    ('Raw Kale'),
    ('Dried Egg White'),
    ('Dill or Kosher Dill Cucumber Pickles'),
    ('Grated Parmesan Cheese'),
    ('Raw Yellow Peaches'),
    ('Prepared Yellow Mustard'),
    ('Raw Green Kiwifruit'),
    ('Raw Nectarines'),
    ('Cheddar Cheese'),
    ('Two Percent Lowfat Cottage Cheese'),
    ('Low Moisture Part-Skim Mozzarella Cheese'),
    ('Dried Whole Egg'),
    ('Dried Egg Yolk'),
    ('Plain Nonfat Greek Yogurt'),
    ('Strawberry Nonfat Greek Yogurt'),
    ('Coconut Oil'),
    ('Ready-to-Serve Spaghetti Marinara Pasta Sauce'),
    ('Ninety-Six Percent Fat Free Pre-Packaged Sliced Deli Ham'),
    ('Pimiento-Stuffed Green Manzanilla Olives'),
    ('Canned Diced Ripe Red Tomatoes'),
    ('Raw Haddock'),
    ('Raw Pollock'),
    ('Drained Light Tuna Canned in Water'),
    ('Raw Lean Select Boneless Beef Eye of Round Roast'),
    ('Raw Lean Select Beef Porterhouse Steak'),
    ('Grilled Lean Choice Bone-In Beef T-Bone Steak'),
    ('Queso Seco Dry White Cheese'),
    ('Whole Milk Ricotta Cheese'),
    ('Swiss Cheese'),
    ('Uncooked Dried Figs'),
    ('Raw Cantaloupe'),
    ('Raw Navel Oranges'),
    ('One Percent Lowfat Milk with Added Vitamins A and D'),
    ('Raw Bartlett Pears'),
    ('Iodized Table Salt'),
    ('Nonfat Skim Milk with Added Vitamins A and D'),
    ('Ready-to-Serve Salsa'),
    ('Two Percent Reduced Fat Milk with Added Vitamins A and D'),
    ('Unprepared Pre-Cooked Beef Breakfast Sausage'),
    ('Pan-Fried Mild Italian Pork Sausage'),
    ('Pan-Fried Pork Chorizo Sausage'),
    ('Whole Milk with Added Vitamin D'),
    ('Raw Mild Turkey Breakfast Sausage Links'),
    ('Granulated Sugar'),
    ('Dry Red Beans'),
    ('Dry Flor de Mayo Beans'),
    ('Dry Brown Beans'),
    ('Dry Tan Beans'),
    ('Dry Carioca Beans'),
    ('Dry Cranberry Beans'),
    ('Dry Light Red Kidney Beans'),
    ('Dry Pink Beans'),
    ('Dry Dark Red Kidney Beans'),
    ('Dry Navy Beans'),
    ('Dry Black Beans'),
    ('Dry Pinto Beans'),
    ('Dry Great Northern Beans'),
    ('Raw Broccoli'),
    ('Restaurant Ketchup'),
    ('Large Egg White'),
    ('Large Egg Yolk'),
    ('Canola Oil'),
    ('Corn Oil'),
    ('Soybean Oil'),
    ('Extra Virgin Olive Oil'),
    ('Large Whole Egg'),
    ('Restaurant Cooked Bacon'),
    ('Unsalted Stick Butter'),
    ('Unbleached Enriched All-Purpose Wheat Flour'),
    ('Unenriched Whole Wheat Flour'),
    ('Unbleached Enriched White Bread Flour'),
    ('Unenriched White Rice Flour'),
    ('Enriched Fine Yellow Corn Flour'),
    ('Salted Stick Butter'),
    ('Raw Red Onions'),
    ('Raw Yellow Onions'),
    ('Raw Garlic'),
    ('Full-Fat Soy Flour'),
    ('Brown Rice Flour'),
    ('Glutinous Rice Flour'),
    ('Unbleached Unenriched Pastry Flour'),
    ('Raw White Onions'),
    ('Raw Ripe and Slightly Ripe Bananas'),
    ('Raw Red Delicious Apples with Skin'),
    ('Raw Fuji Apples with Skin'),
    ('Raw Gala Apples with Skin'),
    ('Raw Granny Smith Apples with Skin'),
    ('Raw Honeycrisp Apples with Skin'),
    ('Peanut Oil'),
    ('Sunflower Oil'),
    ('Safflower Oil'),
    ('Extra Light Olive Oil'),
    ('Lion''s Mane Mushroom'),
    ('Oyster Mushroom'),
    ('Shiitake Mushrooms'),
    ('White Button Mushrooms'),
    ('Shelf-Stable Unsweetened Plain Soy Milk'),
    ('Baby Spinach'),
    ('Mature Spinach'),
    ('Roma Tomato'),
    ('Double Zero Flour'),
    ('Whole Grain Spelt Flour'),
    ('Coarse and Semi-Coarse Semolina Flour'),
    ('Fine Semolina Flour'),
    ('Shelf-Stable Apple Juice from Concentrate with Added Vitamin C'),
    ('Shelf-Stable Purple Grape Juice from Concentrate with Added Vitamin C'),
    ('Shelf-Stable White Grape Juice from Concentrate with Added Vitamin C'),
    ('Shelf-Stable Unfortified Cranberry Juice from Concentrate'),
    ('Refrigerated Unfortified Red Grapefruit Juice Not from Concentrate'),
    ('Shelf-Stable Tomato Juice from Concentrate with Added Ingredients'),
    ('Refrigerated Unfortified Pulp-Free Orange Juice Not from Concentrate'),
    ('Portabella Mushroom'),
    ('King Oyster Mushroom'),
    ('Enoki Mushroom'),
    ('Crimini Mushroom'),
    ('Maitake Mushroom'),
    ('Beech Mushroom'),
    ('Pioppini Mushroom'),
    ('Refrigerated Sweetened Plain Soy Milk'),
    ('Refrigerated Unsweetened Plain Almond Milk'),
    ('Refrigerated Unsweetened Plain Oat Milk'),
    ('Raw Mature Carrots'),
    ('Raw Baby Carrots'),
    ('Raw Green Bell Peppers'),
    ('Raw Yellow Bell Peppers'),
    ('Raw Red Bell Peppers'),
    ('Raw Orange Bell Peppers'),
    ('Low Fat Buttermilk'),
    ('Plain Whole Milk Yogurt'),
    ('Plain Whole Milk Greek Yogurt'),
    ('Crumbled Whole Milk Feta Cheese'),
    ('Almond Flour'),
    ('Whole Grain Oat Flour'),
    ('Potato Flour'),
    ('Creamy Peanut Butter'),
    ('Creamy Sesame Butter'),
    ('Creamy Almond Butter'),
    ('Ground Flaxseed'),
    ('Full Fat Large or Small Curd Cottage Cheese'),
    ('Full Fat Block Cream Cheese'),
    ('Heavy Cream'),
    ('Full Fat Sour Cream'),
    ('Raw Iceberg Lettuce'),
    ('Raw Green Romaine Lettuce'),
    ('Raw Red Leaf Lettuce'),
    ('Raw Green Leaf Lettuce'),
    ('Raw Pine Nuts'),
    ('Raw Whole Almonds'),
    ('Raw English Walnut Halves'),
    ('Raw Pecan Halves'),
    ('Old Fashioned Whole Grain Rolled Oats'),
    ('Whole Grain Steel Cut Oats'),
    ('Raw Pineapple'),
    ('Raw Dark Red Sweet Cherries'),
    ('Raw Green Snap Beans'),
    ('Raw Russet Potatoes Without Skin'),
    ('Raw Red Potatoes Without Skin'),
    ('Raw Gold Potatoes Without Skin'),
    ('Raw Orange-Fleshed Sweet Potatoes Without Skin'),
    ('Raw Celery'),
    ('Raw Cucumber with Peel'),
    ('Raw Green Cabbage'),
    ('Raw Red Cabbage'),
    ('Raw Strawberries'),
    ('Raw Raspberries'),
    ('Raw Blueberries'),
    ('Raw Red Seedless Grapes'),
    ('Raw Green Seedless Grapes'),
    ('Unsweetened Applesauce with Added Vitamin C'),
    ('Amaranth Flour'),
    ('Quinoa Flour'),
    ('Sorghum Flour'),
    ('Buckwheat Flour'),
    ('Rye Flour'),
    ('Barley Flour'),
    ('Cassava Flour'),
    ('Whole Grain Buckwheat'),
    ('Whole Grain Millet'),
    ('Raw Unenriched Long Grain Brown Rice'),
    ('Raw Unenriched Long Grain White Rice'),
    ('Raw Ninety Percent Lean Ground Beef'),
    ('Raw Eighty Percent Lean Ground Beef'),
    ('Raw Ground Pork'),
    ('Raw Ground Chicken with Additives'),
    ('Raw Ninety-Three Percent Lean Ground Turkey'),
    ('Raw Brazil Nuts'),
    ('Raw Cashew Nuts'),
    ('Raw Hazelnuts'),
    ('Raw Peanuts'),
    ('Chestnut Flour'),
    ('Raw Macadamia Nuts'),
    ('Raw Pistachio Nuts'),
    ('Raw Pumpkin Seeds'),
    ('Raw Sunflower Seed Kernels'),
    ('Coconut Flour'),
    ('Dry Cannellini Beans'),
    ('Dry Chickpeas'),
    ('Dry Lentils'),
    ('Dry Black-Eyed Peas'),
    ('Drained and Rinsed Canned Black Beans with Sodium Added'),
    ('Drained and Rinsed Canned Navy Beans with Sodium Added'),
    ('Drained and Rinsed Canned Cannellini Beans with Sodium Added'),
    ('Drained and Rinsed Canned Chickpeas with Sodium Added'),
    ('Drained and Rinsed Canned Dark Red Kidney Beans with Sodium and Sugar Added'),
    ('Drained and Rinsed Canned Light Red Kidney Beans with Sodium and Sugar Added'),
    ('Drained and Rinsed Canned Sweet Green Peas with Sodium and Sugar Added'),
    ('Drained and Rinsed Canned Pinto Beans with Sodium Added'),
    ('Drained and Rinsed Canned Black-Eyed Peas with Sodium Added'),
    ('Drained and Rinsed Canned Great Northern Beans with Sodium Added'),
    ('Raw Boneless Pork Loin'),
    ('Raw Boneless Pork Tenderloin'),
    ('Raw Boneless Skinless Chicken Breast'),
    ('Raw Boneless Skinless Chicken Thigh'),
    ('Raw Choice Boneless Beef Ribeye Steak'),
    ('Raw Choice Boneless Beef Top Round'),
    ('Raw Choice Boneless Beef Chuck Roast'),
    ('Raw Choice Boneless Beef Flank Steak'),
    ('Plain Nonfat Yogurt'),
    ('Solid Monterey Jack Cheese'),
    ('Pasteurized Process American Cheese Singles'),
    ('Sliced Provolone Cheese'),
    ('Solid Oaxaca Cheese'),
    ('Solid Queso Fresco Cheese'),
    ('Solid Cotija Cheese'),
    ('Raw Wild Caught Sockeye Salmon'),
    ('Raw Farm Raised Atlantic Salmon'),
    ('Raw Farm Raised Tilapia'),
    ('Raw Farm Raised Shrimp'),
    ('Raw Wild Caught Atlantic Cod'),
    ('Raw Farm Raised Catfish'),
    ('Refrigerated Pasteurized Lump Blue Swimming Crab'),
    ('Raw Green Zucchini with Skin'),
    ('Raw Yellow Summer Squash with Skin'),
    ('Raw Butternut Squash'),
    ('Raw Acorn Squash'),
    ('Raw Bok Choy'),
    ('Raw Cauliflower'),
    ('Raw Collard Greens'),
    ('Raw Brussels Sprouts'),
    ('Raw Beets'),
    ('Raw Eggplant'),
    ('Canned Whole Tomatoes with Salt Added'),
    ('Canned Tomato Sauce with Salt Added'),
    ('Canned Tomato Paste Without Salt Added'),
    ('Canned Crushed Tomatoes'),
    ('Canned Tomato Puree'),
    ('Raw Apricot with Skin'),
    ('Raw Honeydew Melon'),
    ('Raw Ripe Plantains'),
    ('Raw Underripe Plantains'),
    ('Raw Dry Chia Seeds'),
    ('Raw Dry Bulgur'),
    ('Raw Dry Wild Rice'),
    ('Raw Baby Arugula'),
    ('Raw Green Asparagus'),
    ('Raw Peeled Hass Avocado'),
    ('Raw Unenriched Black Rice'),
    ('Raw Fresh Yellow and White Sweet Corn Kernels'),
    ('Raw Dry Einkorn Grain'),
    ('Raw Dry Pearled Farro'),
    ('Raw Dry Fonio Grain'),
    ('Raw Dry Khorasan Grain'),
    ('Raw Peeled Seedless Mandarin'),
    ('Raw Peeled Tommy Atkins Mango'),
    ('Raw Peeled Ataulfo Mango'),
    ('Raw Dry White or Yellow Masa Harina Corn Flour'),
    ('Raw Green Anjou Pear with Skin'),
    ('Raw Black Plum with Skin'),
    ('Raw Dry Unenriched Red Rice'),
    ('Raw Dry Unenriched White Sorghum Bran'),
    ('Raw Dry White Whole Grain Sorghum'),
    ('Raw Chicken Drumstick with Skin'),
    ('Raw Chicken Thigh with Skin'),
    ('Raw Chicken Wing with Skin'),
    ('Raw Chicken Breast with Skin'),
    ('Raw Ground Lamb'),
    ('Raw Ground Bison'),
    ('Raw Beef New York Strip Steak'),
    ('Raw Beef Tenderloin Steak'),
    ('Raw Beef Top Sirloin Steak'),
    ('Raw Center Cut Pork Chop'),
    ('Raw Pork Belly with Skin'),
    ('Raw Peeled and Seeded Pawpaw'),
    ('Raw Peeled and Seeded Pie Pumpkin'),
    ('Raw Peeled and Seeded Spaghetti Squash'),
    ('Raw Peeled Rutabaga'),
    ('Raw Blackberries'),
    ('Raw Husked Tomatillos'),
    ('Raw Destemmed Napa Cabbage Leaves'),
    ('Raw Trimmed Leeks with Bulb and Greens'),
    ('Raw Trimmed Green Onions with Bulb and Greens'),
    ('Raw Peeled and Trimmed Shallot Bulbs'),
    ('Shelf-Stable Prune Juice'),
    ('Shelf-Stable Pomegranate Juice from Concentrate'),
    ('Shelf-Stable Tart Cherry Juice from Concentrate'),
    ('Drained Salted Anchovies Canned in Olive Oil'),
    ('Raw Beet Greens'),
    ('Raw Fennel Bulb'),
    ('Frozen Wild Caught Halibut'),
    ('Frozen Wild Caught Lobster Tail'),
    ('Frozen Wild Caught Mahi Mahi'),
    ('Raw Parsnips'),
    ('Raw Seeded Banana or Hungarian Wax Peppers'),
    ('Raw Seeded Jalapeno Peppers'),
    ('Raw Seeded Poblano Peppers'),
    ('Raw Seeded Serrano Peppers'),
    ('Raw Radicchio'),
    ('Raw Red Radishes'),
    ('Frozen Wild Caught Patagonian Bay Scallops'),
    ('Frozen Wild Caught Sea Scallops'),
    ('Frozen Wild Caught Chilean Sea Bass'),
    ('Frozen Wild Caught Snapper'),
    ('Frozen Snow Crab Legs'),
    ('Frozen Squid Tubes'),
    ('Frozen Wild Caught Swordfish'),
    ('Frozen Wild Caught Ahi or Yellowfin Tuna'),
    ('Raw Turnips'),
    ('Raw Seedless Watermelon Flesh'),
    ('Raw Seedless Watermelon Rind')
) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM ingredient_suggestions s WHERE lower(s.name) = lower(v.name))
ORDER BY lower(v.name);
