spring.application.name=granary

spring.datasource.url=jdbc:h2:mem:granarydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

app.jwt.secret=88b732b9e66af19d163247973e2e55a679427f3b43d3941b04d3e1b771d46642
app.jwt.expiration=86400000

spring.profiles.active=dev

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
 
app.upload.dir=uploads/recipe-images
app.cors.allowed-origins=http://localhost:3000

logging.level.root=INFO
logging.level.com.example.granary=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE