app.jwt.secret=88b732b9e66af19d163247973e2e55a679427f3b43d3941b04d3e1b771d46642
app.jwt.expiration=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/granary
spring.datasource.username=granary
spring.datasource.password=granary_dev_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

app.cors.allowed-origins=http://localhost:5173

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE